### ISSUE TITLE
Great Project

### ISSUE THREAD

**Issue by GotchaLogic** [vsnz/TradingView-Webhook-Bot#13]
If you want to hit me up on Discord Gotcha#9318 I am working on a automation bot and I think we could really do some neat things together with this.

**Comment by tabullarasa** [comment]
I cant add ya man add me tabularasa#2437 yes we can talk thanks

**Comment by GotchaLogic** [comment]
Added

**Comment by vsnz** [comment]
Hi @GotchaLogic,

Thanks for reaching out. At the moment I am fairly busy and wont have time for another project. Good luck with your bot though!
