### ISSUE TITLE
> module 'config' has no attribute 'telegram'

### ISSUE THREAD

**Issue by JaapS6** [vsnz/TradingView-Webhook-Bot#14]
First of all thanks for sharing your work. I have an issue when running this on my local machine (windows10). I don't plan on doing so long term as I am aware it's better on a VPS (plus I use a VPN and have to turn it off to run this) but am just trying to get it to work first of all.

The issue is when trying to forward to telegram, I get this error: > module 'config' has no attribute 'telegram'. I do get: Alert Received & Sent! though.

I am assuming it must be an issue with my setup since the bot seems to work for other people as I've not seen this raised before, but I'm not sure what I am doing wrong.

If any further detail is required please let me know.

**Comment by vsnz** [comment]
Hi @JaapS6,

Thanks for bringing up that issue. The last commit should fix it. Could you please update your git and report back if its working now?

Thank you.

**Comment by JaapS6** [comment]
Hi @vsnz yes that fixed it. Thanks for responding so quickly.

**Comment by vsnz** [comment]
Awesome, thanks for the update.
