### ISSUE TITLE
Error can't parse entities: can't find end of the entity starting at byte offset 25

### ISSUE THREAD

**Issue by Rhydderch** [vsnz/TradingView-Webhook-Bot#18]
Hello,

Thank you for this awesome project. The instructions were clear and I could set up my server with your referral link.

Now I am getting an issue :
![image](https://user-images.githubusercontent.com/3197629/102654319-a4aee500-4170-11eb-8234-50b6687b3b7f.png)

How could I solve this?
Also, is there a way to use the security code without having to put it into the alert ? Can I put it in the webhook url ?

Best,
Rhydderch

**Comment by vsnz** [comment]
Hello Rhydderch,

If you have set `sec_code` in config.py you'd have to mention it in the alert as well. Else wise the alert will be refused.

You could change `/webhook` from your URL to anything you wish. This can be done in [main.py](https://github.com/vsnz/TradingView-Webhook-Bot/blob/2f5274436bf8546d299b9c0394ab90fb3784e4c5/main.py#L15). So it could result in something like `http://<YOUR-IP>/somerandomword`.

**Comment by Rhydderch** [comment]
Hello vsnz,

Thank you for your answer and clarification. And for answering so quickly.

I still have the "can't parse entities" error. It seems to be due to the underscore; however, I absolutely need to use it...
Do you know how to fix this error?
I tried to [google it](https://www.google.be/search?sxsrf=ALeKk005XA2pToIAlt7SPd4y43n55lga2w%3A1603180448164&source=hp&ei=oJeOX_2VB4G4kwX5_5aICQ&q=Error+can%27t+parse+entities%3A+can%27t+find+end+of+the+entity+starting+at+byte+offset&btnK=Google+Search&oq=network+drawing&gs_lcp=CgZwc3ktYWIQAzIFCAAQyQMyAggAMgIIADICCAAyAggAMgIIADICCAAyAggAMgIIADICCAA6BwgjEOoCECc6BAgjECc6CAgAELEDEMkDOgUIABCxAzoICAAQsQMQgwE6CAguEMcBEKMCOgIILjoLCC4QsQMQxwEQowI6CwguELEDEMcBEK8BOgUIABDLAToECAAQClDqEFitJ2C0J2gBcAB4AIABcIgB6QiSAQQxMS4ymAEAoAEBqgEHZ3dzLXdperABCg&sclient=psy-ab&ved=0ahUKEwj95fvI2MLsAhUB3KQKHfm_BZEQ4dUDCAc&uact=5). It seems it could be due to the python telegram bot

**Comment by Rhydderch** [comment]
Update : I solved it by parsing the underscore as follows : #USDT\_BTC :) !

**Comment by vsnz** [comment]
The underscore you are using has to be escaped by putting a backslash (`\`) before it. So for example: `#USDT\_BTC`.

Let me know if that fixed your problem.

**Comment by vsnz** [comment]
> Update : I solved it by parsing the underscore as follows : #USDT_BTC :) !

Just saw your reply. Glad you figured it out. I will then close the issue now.
