### ISSUE TITLE
Feature idea : support multiple telegram and discord channels

### ISSUE THREAD

**Issue by Rhydderch** [vsnz/TradingView-Webhook-Bot#19]
Hello again,

Looking at the config.py file, I see we can add one telegram channel to the code. To my best of knowledge, I don't think it is possible to maintain multiple telegram or discord channels ?

A "easy" (I don't know if it is hard to code) fix could be to create an option in the config file to support multiple channels in telegram and/or discord. If this is = TRUE, then the user can set the telegram channel number in the alert message (or perhaps in the webhook url). The channel id would be captured by the server and then the server would send the alert to it.

This could be very useful to handle various bots on one server and, for example, create different discord channels for different types of information.

I'm curious of what you'll think of this idea.

Best,
Rhydderch

**Comment by vsnz** [comment]
Yes that sounds do-able. I can most certainly add that feature. I will add it to my list, shouldn't;t take too long to complete.

**Comment by Rhydderch** [comment]
Great. Thank you!

**Comment by vsnz** [comment]
Hi @Rhydderch,

I have updated the bot and also implemented your feature request. Be sure to read the [installation](https://github.com/vsnz/TradingView-Webhook-Bot#installation) steps one more time since the mechanics have changed. 

Let me know if anything is not working.

**Comment by Hades-Corps** [comment]
I am running this on an Ubuntu 24 on LXC with a reverse proxy pointing to it. Somehow, this is not stable. Well, either that or I got the JSON wrong.
"telegram": "channel1",
"telegram": "channel2",
Works once, then subsequence calls would not works.

"telegram": ["channel 1", "channel2"], 
Does not work at all.
