### ISSUE TITLE
Alert via email

### ISSUE THREAD

**Issue by gibscarter** [vsnz/TradingView-Webhook-Bot#21]
Hey, thank you for such great work!

Any possibilities you could add alternate alerts option like via email? (not webhook)
This could be very useful for someone (like-me) who want to run it through localhost, as some provider blocks port and need an extra effort to open it 

Thank you!

**Comment by vsnz** [comment]
Hi,

Keeping track of an email account is always a pain, at least in my past experience. For that reason I am not really interested in writing a bot for that. On top of that the delivery method is just not as smooth as a webhook. Webhooks execution is almost instant.

When running the bot of your local network you most likely have to open port 80, that is right. If port 80 is blocked by your ISP you may have to forward it to something like 8080.

**Comment by gibscarter** [comment]
"If port 80 is blocked by your ISP you may have to forward it to something like 8080."

Do u have any reference/link how do i do this?

**Comment by vsnz** [comment]
Depends on your setup. If using Apache [this](https://alychitech.com/how-to-forward-ports-using-apache/) guide might be helpful.
