### ISSUE TITLE
Telegram Markdown

### ISSUE THREAD

**Issue by NAZARETH64** [vsnz/TradingView-Webhook-Bot#22]
Exellent Project!

Does the markdown doesn't work properly? I typed "<b>text</b>" on the message alert and it forwarded with code included

**Comment by vsnz** [comment]
Hi,

markdown for telegram and discord should work just fine.

Could you please share your TradingView alerts message As well as the output message?

**Comment by NAZARETH64** [comment]
message: Open Long <.b>{{ticker}}</.b> arround {{close}}

output: Open Long <.b>XBTUSD</.b> arround 23591

(without . )

**Comment by NAZARETH64** [comment]
hey sorry, markdown worked fine.. 
Should have used v2 style instead of html

Thanks!

**Comment by vsnz** [comment]
Oh right, its v2. Glad its working now.
