### ISSUE TITLE
'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by babovand** [vsnz/TradingView-Webhook-Bot#25]
Hi!

First wanted to say this is a very nice project and give my thanks.

I've an Issue. Every time the server gets an alert this is what i see in the console.

```
^C(TradingView-Webhook-Bot) ubuntu@web:~/bot/TradingView-Webhook-Bot$ python main.py
Serving on http://xxxx:7080
[X] 2021-01-12 14:12:09 Error:
> 'NoneType' object is not subscriptable
[X] 2021-01-12 14:14:22 Error:
> 'NoneType' object is not subscriptable
[X] 2021-01-12 14:15:59 Error:
> 'NoneType' object is not subscriptable
```

**Comment by babovand** [comment]
Solved it
The error was in my telegram message, the syntax i wrote was wrong

**Comment by vsnz** [comment]
Hi,

Glad to hear that you could solve issue yourself.
