### ISSUE TITLE
Help getting plain text

### ISSUE THREAD

**Issue by Dirtbikes1** [vsnz/TradingView-Webhook-Bot#27]
Trading view will send json data if there is json data being used, but it will also send plain text if that is all that is in the message.

I got the bot working with json, but i really need to get it working with just plain text. 

So in Tradingview my output would be as an example:

BINANCE
#USDT_BTC
LONG

Could you give me an example of what code I need to change in the main.py to get plain text data?

Thanks.

**Comment by vsnz** [comment]
Hi,

My bot used to behave that way, it simply forwards TradingView's message dialog box. You can take a look in the archive [here](https://github.com/vsnz/TradingView-Webhook-Bot/tree/2f5274436bf8546d299b9c0394ab90fb3784e4c5).

**Comment by Dirtbikes1** [comment]
Well I am getting close. I had to use the handler.py also. I can get it to send the lines to telegram but I run into an error when using an underscore. 

Can't parse entities: can't find end of the entity starting at byte offset 13

Line I an trying to send:

#USDT_BTC

Any ideas? Thanks so much.

**Comment by Dirtbikes1** [comment]
Nevermind, I got it. Using MarkdownV2 and escapes work, but the better solution was to use HTML. THANK YOU SO MUCH!!

**Comment by vsnz** [comment]
Awesome, glad it's working now. Let me know if your running into any issue moving forward.

I mentioned my BTC address in my readme [here](https://github.com/vsnz/vsnz/blob/main/assets/donations/DONATION.md). Any appreciation is welcome.
