### ISSUE TITLE
Start bot on reboot Linux

### ISSUE THREAD

**Issue by Dirtbikes1** [vsnz/TradingView-Webhook-Bot#28]
Hi! I have this running on latest Ubuntu Desktop. Everything is working. 

I was wondering if you could provide some instruction for using systemd to make this run on a reboot (without a user logged in). I am worried if my system reboots the bot is going to stop working. 

I am a not a complete novice to Linux, but I am not an expert either. I see that I would need a .service file located in etc/systemd/system, but I am unsure exactly what to put in there. 

P.S. Sending you some BTC right now for your trouble. 

Thanks!

**Comment by vsnz** [comment]
Hi, glad its all working now and thanks the donation :).

You'd have two options to run the app in the background as well as on boot. Systemd and [PM2](https://pm2.io). I personally prefer PM2. To [install](https://pm2.io/docs/runtime/guide/installation/) PM2 issue the following command:

`sudo npm install pm2 -g`

Be sure npm is installed on your machine. When the installation finished go into your bot folder in your venv, and start the bot with the following command:

`pm2 start main.py --name TV-Webhook-Bot`

To auto start the bot on boot type:

`pm2 startup` & `pm2 save`

You can see the logs with `pm2 log`.

Hope that helps and let me know it anything is not working.

**Comment by Dirtbikes1** [comment]
Awesome. I will try it now. Thanks.

**Comment by Dirtbikes1** [comment]
You are totally awesome man! Working perfect! I can now get my bots moved over to my own server instead of relying on somebody else. I will send you some more BTC soon! Thank you so much.

**Comment by vsnz** [comment]
Awesome, glad to hear that. Enjoy the bot!
