### ISSUE TITLE
Timestamp in logs

### ISSUE THREAD

**Issue by Dirtbikes1** [vsnz/TradingView-Webhook-Bot#29]
I found a slight bug. The timestamp is always the same time in the logs. I fixed it by moving "timestamp = time.strftime("%Y-%m-%d %X")" from the top of the code to under the "webhook" portion. This is in the main.py. Thanks!

**Comment by vsnz** [comment]
Oh, didn't notice that. Will be fixed shortly.

**Comment by vsnz** [comment]
I  have fixed the timestamp bug in the last [commit](https://github.com/vsnz/TradingView-Webhook-Bot/commit/025dbcc58d52f888b62f2d89f69fd7a047ffc05e).
