### ISSUE TITLE
NoneType object not subscriptable

### ISSUE THREAD

**Issue by nikaa213** [vsnz/TradingView-Webhook-Bot#30]
Hi,

First of all. Thank you for the hard work. 

I followed the tutorial, everything went flawlessy except the last part after python main.py.

![image](https://user-images.githubusercontent.com/77930297/105636154-32b07680-5e67-11eb-8a19-2ad47e18b28c.png)

I'm getting the following error. Can't seem to resolve it.

Thanks for the support.

**Comment by vsnz** [comment]
Hi,

That's most likely a syntax issue. Could you please share your alerts message?

**Comment by nikaa213** [comment]
Hey VSNZ,

Thanks for the fast reply. I see that it only works like this:

{"key": "170147", "msg":
"Possible 4H uptrend detected on {{ticker}} at `{{close}}`"}

When I do:

{"key": "170147", "msg":  {{ticker}}
"Possible uptrend detected on 4H at `{{close}}`"}

it does not.

**Comment by vsnz** [comment]
Oh, OK. I would have to look into that. Which symbol were you using?

**Comment by nikaa213** [comment]
Can you explain what do you mean with "symbol"?

It happens with every crypto ticker for example.

**Comment by vsnz** [comment]
OK, that's enough for me to know. Thanks.

**Comment by nikaa213** [comment]
Thanks for the help VSNZ! Have a nice evening!

**Comment by shadowdub** [comment]
Have the same issue. I attached my alert below:

{"key":  "passw" , "telegram": "-chatid", "discord": " ", "msg": "📈📊📉 ‼️ `Buy` ‼️ 📈📊📉\n\nExchange: `{{exchange}}`\n\nTicker: #{{ticker}} \n\n`Buy` at: `{{close}}`"}

**Comment by vsnz** [comment]
@shadowdub @nikaa213:

I have pushed a new commit which fixed an underscore issue. Could you update your bot and let me know if that also fixes your problems? Thank you.

**Comment by vsnz** [comment]
Closing this issue now.
