### ISSUE TITLE
Tradingview web hook alert bot

### ISSUE THREAD

**Issue by ambitious-samin321** [vsnz/TradingView-Webhook-Bot#31]
I'm having some trouble installing the bot I'm somewhat new to coding but not entirely new and ill send you pics of my problems. As well as pics of what i have done so far.

First picture is the file config.py, please let me know if i have followed your instructions correctly for that file. 
<img width="1428" alt="1st pic" src="https://user-images.githubusercontent.com/40134016/105647167-b7a08d80-5e71-11eb-8899-1b0bddd16d40.png">

Second picture is the command -ls, I just wanted to make sure i had all the files.
<img width="508" alt="2nd pic" src="https://user-images.githubusercontent.com/40134016/105647172-bd966e80-5e71-11eb-9fc6-54ebb3f07b9e.png">

third picture is me running python main.py and python3 main.py
i am getting errors for both and i dont know why.
<img width="541" alt="3rd picture" src="https://user-images.githubusercontent.com/40134016/105647176-c25b2280-5e71-11eb-97df-56add4657390.png">

4th picture is just to make sure I am inputting the information in the tradingview correctly for usage.
<img width="373" alt="4th picture" src="https://user-images.githubusercontent.com/40134016/105647179-c6874000-5e71-11eb-86dd-a811b8c189b5.png">

**Comment by vsnz** [comment]
Hi,

I am seeing a few issues. Let me go over them. 

Image 1:
You'd have to set `send_discord_alerts` to `True`.

Image 2:
Looks all good. 

Image 3:
You did not install flask. Did you activate your Virtual Environment and ran `pip install -r requirements.txt`? It is explained in the [installation steps](https://github.com/vsnz/TradingView-Webhook-Bot#installation), point 3 & 4.

Image 4:
The `Webhook URL` would have to be updated so it points to your VPS.

Hope that helps. Let me know if you run into amt further issues.

**Comment by vsnz** [comment]
Closing this issue now. If you are still having problems or something is not working just open a new issue.
