### ISSUE TITLE
Deploying on Heroku/Github - {"sender": ["This field is required"]}

### ISSUE THREAD

**Issue by ZeroSum000** [vsnz/TradingView-Webhook-Bot#32]
Thank you soo much for all you have done for us!!! 

I have successfully deployed this to my cloud platform using Heroku/Github as the host and updated the config file accordingly. I  tried to trouble shoot this by means of googling but have not been able to figure out what is going wrong.  I am receiving the error - Webhook status code 400: {"sender": ["This field is required"]} however I do not see a required field for this in the data

**Comment by ZeroSum000** [comment]
I GOT IT!!!!! lol wow.   For anyone that has trouble, the steps I took were the discord_webhook must have /github at the end in the config.py and then the message alert does not need the /github at the end and simple just the api code.

**Comment by vsnz** [comment]
Awesome! Glad you've figured it out yourself!
