### ISSUE TITLE
Running on more than 20 bots

### ISSUE THREAD

**Issue by Dirtbikes1** [vsnz/TradingView-Webhook-Bot#34]
Hi, I am getting errors and not all of my alerts are going through. It seems I get about 20 of them. I am currently running 40 bots. I am sending alerts every 15 minutes, but I am getting this error....

Flood control exceeded. Retry in 40.0 seconds

I am also getting errors......

WARNING:waitress.queue:Task queue depth is 22

Any help will be appreciated. Thanks.

**Comment by vsnz** [comment]
Hi,

I personally never ran into such a warning so I can't really tell you what to do. I'll keep this issue open so someone else can chip in.

**Comment by Dirtbikes1** [comment]
I found this. It seems I need to create a queue of some sort so I am not sending more than 20 messages per minute. I am also trying to find something in tradingview that would delay sending, but to no avail yet. Thanks. https://telegra.ph/So-your-bot-is-rate-limited-01-26

**Comment by vsnz** [comment]
Yes, Telegram rate limits bots. I usually run into those issue when sending messages to several users at once. But aren't you using 20 different Telegram Bots?

**Comment by Dirtbikes1** [comment]
No its one bot.

**Comment by vsnz** [comment]
Ok, understand. That could be handled internally by raising an exception and only then `time.sleep(0.5)`.

**Comment by vsnz** [comment]
Or just use more than 1 Bot ;)

**Comment by Dirtbikes1** [comment]
Unfortunately I can only send to one bot. I can't go into detail but this is for a retail purpose. I think a delay at Tradingview would be the best solution, as I am getting issues using another way also, but have yet to find a way to do that. Thanks. I wish there was an easy way to simply delay signals from Tradingview.

**Comment by vsnz** [comment]
As said, you can handle it from the code side as well. IF the error occurs sleep for 0.5 seconds. But you need a bit of coding knowledge. I can share my code but that is for a different Telegram Framework.

```py
try:
    sended=False
    while not sended:
        try:
            bot.send_message(config.channel, data['msg'].encode('latin-1','backslashreplace').decode('unicode_escape')), parse_mode='Markdown')
        except ApiTelegramException as err:
            if err.result_json['error_code']==429:
                time.sleep(0.5) # wait for 0.5 seconds
            else:
                raise # reraise exception if error_code is not 429
        else:
            sended = True
except Exception as e:
    pass
```

**Comment by Dirtbikes1** [comment]
Thanks, I have to do other things for a few hours, but will get back at this problem later. I appreciate all of your help. I think a simple Tradinview alert delay will solve all of my problems on two different platforms. I think this might work. Thanks. https://www.tradingview.com/script/2lMZ7ZJB-Early-Delayed-Signal-Function/

**Comment by vsnz** [comment]
Sounds good. I will close the issue for now. If you still got questions just open a new one or reply here again.
