### ISSUE TITLE
Run with other ports?

### ISSUE THREAD

**Issue by NAZARETH64** [vsnz/TradingView-Webhook-Bot#35]
Hey, is it possible to listen on other port than 80?
I have an app that listen on same port (80)..

From what i know, 2 apps cannot listen to the same port, thank you!

**Comment by vsnz** [comment]
Hi,

Yes it is possible **but** TradingView only allows port 80/443. You could either look into port forwarding or running Flask behind Apache or Nginx.

**Comment by NAZARETH64** [comment]
Do i have to edit some file?

**Comment by vsnz** [comment]
You won't have to edit any file from Bot but depending on which option you chose you obviously have to edit and update settings on your server. Port forwarding can be done through the default firewall UFW.
