### ISSUE TITLE
You are being rate limited

### ISSUE THREAD

**Issue by nikaa213** [vsnz/TradingView-Webhook-Bot#36]
Hi VSNZ

I have updated the bot. I am now encountering a new error:

I am being rate limited by Discord, code: 429.

Is this a known issue?

**Comment by vsnz** [comment]
You might've sent to many messages at once. By doing so you will always be rate limited. You can find a possible solution [here](https://github.com/vsnz/TradingView-Webhook-Bot/issues/34#issuecomment-777618712).

**Comment by nikaa213** [comment]
Thanks
