### ISSUE TITLE
'NoneType' error

### ISSUE THREAD

**Issue by stoofman** [vsnz/TradingView-Webhook-Bot#37]
When the bot is running and receives a tradingview alert, it is giving this error:

'NoneType' object is not subscriptable

**Comment by vsnz** [comment]
Hi, 

That is usually a wrong formatted json string. Please send me syntax you pasted into your TradingView alerts dialog.

**Comment by stoofman** [comment]
Hi I think you are right, I noticed { } were missing in my TradingView alert.
This is my current TradingView alert format 👍 
{
 "key": "AAD231DFEw",
 
 "msg": "Long "
}

and now I am getting  this error : 

2021-02-23 15:21:00 Alert Received & Sent!
ERROR:discord_webhook.webhook:[1/1] Webhook status code 404: {"message": "404: Not Found", "code": 0}

**Comment by vsnz** [comment]
Did you set your Discord Webhook in [config.py](https://github.com/vsnz/TradingView-Webhook-Bot/blob/7ae204ed9300c17cb80980639e4cb9cabe25b6c1/config.py#L21)?

**Comment by stoofman** [comment]
yes like this : 

# Discord Settings
send_discord_alerts = True
discord_webhook     = 'https://discord.com/api/webhooks/811726880858498546/m1D0ONAxbaVsddfHHGn124tgAyrPoERfFHjl3CNmIHaLuC2r4xx3'    # Discord Webhook URL (https://support.discordapp.com/hc/de/articles/228383668-Webhooks-verwenden)

**Comment by vsnz** [comment]
Oh OK. Please do not include:
`https://discord.com/api/webhooks/`

A valid input would be:
`discord_webhook="811726880858498546/m1D0ONAxbaVsddfHHGn124tgAyrPoERfFHjl3CNmIHaLuC2r4xx3"`

**Comment by stoofman** [comment]
awesome ,that works ! thank you so much ! :-)
